Update README.md
vvkrss/java pull request #1
Opened 2023-09-14 17:27 UTC by vvkrss

2023-09-14 20:20 UTC, KozlovAV426 requested changes

2023-09-14 20:20 UTC, KozlovAV426 commented on README.md
> +import java.math.BigInteger;
В readme.md не стоило все-таки писать решение) Нужно создать отдельный файл с расширением .java и в него перенести

2023-09-14 20:20 UTC, KozlovAV426 commented on README.md
> +        int maxim = Math.max(x, Math.max(y, z));
на будущее - maxim - не самое лучшее название,  тогда уж maximum

2023-09-14 20:20 UTC, KozlovAV426 commented on README.md
> +        int summ = 0;
почему summ? уж тогда sum

2023-09-14 20:20 UTC, KozlovAV426 commented on README.md
> +        int art = summ / nums.length;
зачем делать int art =..., а потом return art; тогда уж сразу return sum / nums.length;

2023-09-14 20:20 UTC, KozlovAV426 commented on README.md
> +        int equal = 0, diag = 0, current_1, current_2;
объявление каждой переменной с новой строчки
camelCase для нейминга, то есть не current_1, а current1, но цифры в нейминге лучше не использовать - firstCurrent

2023-09-14 20:20 UTC, KozlovAV426 commented on README.md
> +        int[] reverse_array = new int[arr.length];
camelCase

2023-09-14 20:20 UTC, KozlovAV426 commented on README.md
> +    static int swap(int first, int second) {
не совсем понял смысл swap, который возвращает first

2023-09-14 20:52 UTC, ASemenovng commented on README.md
> +    static int swap(int first, int second) {
Тут видимо имелась в виду чуть чуть другая реализация, а именно:

```java
static int swap (int x, int y) {
    return x;
  }

И в main:
  int x = 3;
  int y = 4;
  y = swap(x, x = y);
```
Но в целом перед использованием какой-либо функции стоит убедиться в том, что она правильно работает

2023-09-30 12:24 UTC, KozlovAV426 commented
Нужно вынести решение в отдельный java файл, а не писать его в readme.Md + остались неисправленные замечания по поводу camelCase

2023-09-30 12:26 UTC, KozlovAV426 requested changes

2023-09-30 12:26 UTC, KozlovAV426 commented on README.md
> +import java.math.BigInteger;
нужно сделать

2023-09-30 12:26 UTC, KozlovAV426 commented on README.md
> +        int[] reverse_array = new int[arr.length];
здесь поправить

2023-10-15 23:01 UTC, ASemenovng requested changes

2023-10-15 23:01 UTC, ASemenovng commented on HW1
> +public static void main(String[] args) {
Файл должен быть .java
Должен быть public класс с таким же именем, а не просто методы подряд

2023-12-01 16:25 UTC, merged